### ISSUE TITLE
Exp bugged

### ISSUE THREAD

**Issue by shimelno** [Mytherin/Tibialyzer#90] opened 2016-06-06 06:39 UTC
when i'm in a hunt sometime my exp increase without i kill a monster, it is like each hit i gain some exp, and when i kill the moster beside the xp already received i gain the original amount that the monster give. normally when i'm hunting demons with bonus stamina i gain aproximately 10k of xp which i should only gain 9k.

and a sugestion, you should put the screenshot to save the date on the screenshot, i know that it save in the name of the file, but some people, like me, like to change the name of the file. :)

**Comment by Mytherin** [comment] 2016-06-06 08:54
This is likely caused by duplicate messages being scanned. Are you using the flash client or using the "Scan Entire Memory" option for the stand-alone client?

**Comment by shimelno** [comment] 2016-06-07 05:14
experience computation: standard(tibia client style)
scan entire memory: scan internal tabs structure.

i'm using stand-alone client. and basically the tibialyze is with default settings, i just mark the enable screanshoot tab

**Comment by jeremgod** [comment] 2016-06-07 13:51
The reason for this is since the new client mana potions give mana but the
string starts with "You have gained XXX mana." Tibialyzer thinks that this
is "You have gained XXX experience" therefore creating an error in the
exp/h I have noticed that last night

**Comment by shimelno** [comment] 2016-06-07 16:49
hey man, i just test here, it is realy this :) thank you Jeremgod.

Mytherin, when you think you will solve this?

**Comment by EricArndt** [comment] 2016-06-07 17:18
Should be a simple fix. Here is the offending code snippet

logMessage.Length > 17 && logMessage.Substring(5, 12) == " You gained "

Should just be able to exclude strings ending in "mana." I'm at work or I'd submit the fix.

**Comment by oufooz** [comment] 2016-07-26 06:27
Any Updates on this ?

**Comment by Mytherin** [comment] 2016-07-26 21:53
This issue should already be fixed in Tibialyzer v1.3.0.

**Closed** 2016-08-30 11:53 UTC
